{{ $ca := genCA "terrak8s.io" 3720 }}
  {{ $cn := printf "%s-svc.%s.svc" .Values.controller.name .Values.controller.namespace}}
  {{- $altNames := list (printf "%s-svc.%s.svc" .Values.controller.name .Values.controller.namespace) (printf "%s-svc.%s" .Values.controller.name .Values.controller.namespace)}}
  {{ $cert := genSignedCert $cn nil $altNames 3720 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: {{ .Values.controller.namespace}}
  labels: {{- include "terrak8s.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.key: {{ b64enc $cert.Key }}
  tls.crt: {{ b64enc $cert.Cert }}

---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ printf "mutate-%s" .Values.controller.name }}
  labels: {{- include "terrak8s.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1beta1
    name: webhook-mutate.terrak8s.io
    clientConfig:
      service:
        name: {{ printf "%s-svc" .Values.controller.name }}
        namespace: {{ .Values.controller.namespace}}
        path: "/mutate-sql-terrak8s-io-v1alpha1-postgresql"
      caBundle: {{ b64enc $ca.Cert}}
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["sql.terrak8s.io"]
        apiVersions: ["v1alpha1"]
        resources: ["postgresqls"]
    sideEffects: None
    failurePolicy: Fail

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ printf "validator-%s" .Values.controller.name }}
  labels: {{- include "terrak8s.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1beta1
    name: webhook-validator.terrak8s.io
    clientConfig:
      service:
        name: {{ printf "%s-svc" .Values.controller.name }}
        namespace: {{ .Values.controller.namespace}}
        path: "/validate-sql-terrak8s-io-v1alpha1-postgresql"
      caBundle: {{ b64enc $ca.Cert}}
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["sql.terrak8s.io"]
        apiVersions: ["v1alpha1"]
        resources: ["postgresqls"]
    sideEffects: None
    failurePolicy: Fail