apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-pdb" .Values.controller.name }}
  namespace: {{ .Values.controller.namespace}}
  labels: {{ include "terrak8s.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels: {{ include "terrak8s.selectorLabels" . | nindent 8  }}