apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc" .Values.controller.name }}
  labels: {{- include "terrak8s.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
  {{- include "terrak8s.selectorLabels" . | nindent 4 }}