apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "sa-%s" .Values.controller.name }}
  namespace: {{ .Values.controller.namespace}}
  labels: {{- include "terrak8s.labels" . | nindent 4 }}
