// +build !ignore_autogenerated

/*
Copyright 2020 The Terrak8s-operator authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSql) DeepCopyInto(out *PostgreSql) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSql.
func (in *PostgreSql) DeepCopy() *PostgreSql {
	if in == nil {
		return nil
	}
	out := new(PostgreSql)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgreSql) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSqlList) DeepCopyInto(out *PostgreSqlList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgreSql, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSqlList.
func (in *PostgreSqlList) DeepCopy() *PostgreSqlList {
	if in == nil {
		return nil
	}
	out := new(PostgreSqlList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgreSqlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSqlSpec) DeepCopyInto(out *PostgreSqlSpec) {
	*out = *in
	out.Project = in.Project
	out.RemoteState = in.RemoteState
	in.BucketConfig.DeepCopyInto(&out.BucketConfig)
	in.SqlInstance.DeepCopyInto(&out.SqlInstance)
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]PostgresInstanceDatabases, len(*in))
		copy(*out, *in)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]PostgresInstanceDatabaseUsers, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSqlSpec.
func (in *PostgreSqlSpec) DeepCopy() *PostgreSqlSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSqlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSqlStatus) DeepCopyInto(out *PostgreSqlStatus) {
	*out = *in
	out.Output = in.Output
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSqlStatus.
func (in *PostgreSqlStatus) DeepCopy() *PostgreSqlStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSqlStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresInstanceDatabasePassword) DeepCopyInto(out *PostgresInstanceDatabasePassword) {
	*out = *in
	out.SecretKeyRef = in.SecretKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresInstanceDatabasePassword.
func (in *PostgresInstanceDatabasePassword) DeepCopy() *PostgresInstanceDatabasePassword {
	if in == nil {
		return nil
	}
	out := new(PostgresInstanceDatabasePassword)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresInstanceDatabasePasswordSpec) DeepCopyInto(out *PostgresInstanceDatabasePasswordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresInstanceDatabasePasswordSpec.
func (in *PostgresInstanceDatabasePasswordSpec) DeepCopy() *PostgresInstanceDatabasePasswordSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresInstanceDatabasePasswordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresInstanceDatabaseUsers) DeepCopyInto(out *PostgresInstanceDatabaseUsers) {
	*out = *in
	out.Password = in.Password
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresInstanceDatabaseUsers.
func (in *PostgresInstanceDatabaseUsers) DeepCopy() *PostgresInstanceDatabaseUsers {
	if in == nil {
		return nil
	}
	out := new(PostgresInstanceDatabaseUsers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresInstanceDatabases) DeepCopyInto(out *PostgresInstanceDatabases) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresInstanceDatabases.
func (in *PostgresInstanceDatabases) DeepCopy() *PostgresInstanceDatabases {
	if in == nil {
		return nil
	}
	out := new(PostgresInstanceDatabases)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresInstanceOutput) DeepCopyInto(out *PostgresInstanceOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresInstanceOutput.
func (in *PostgresInstanceOutput) DeepCopy() *PostgresInstanceOutput {
	if in == nil {
		return nil
	}
	out := new(PostgresInstanceOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresInstanceSettingsBackupConfiguration) DeepCopyInto(out *PostgresInstanceSettingsBackupConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresInstanceSettingsBackupConfiguration.
func (in *PostgresInstanceSettingsBackupConfiguration) DeepCopy() *PostgresInstanceSettingsBackupConfiguration {
	if in == nil {
		return nil
	}
	out := new(PostgresInstanceSettingsBackupConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresInstanceSettingsDatabaseFlags) DeepCopyInto(out *PostgresInstanceSettingsDatabaseFlags) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresInstanceSettingsDatabaseFlags.
func (in *PostgresInstanceSettingsDatabaseFlags) DeepCopy() *PostgresInstanceSettingsDatabaseFlags {
	if in == nil {
		return nil
	}
	out := new(PostgresInstanceSettingsDatabaseFlags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresInstanceSettingsIpConfiguration) DeepCopyInto(out *PostgresInstanceSettingsIpConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresInstanceSettingsIpConfiguration.
func (in *PostgresInstanceSettingsIpConfiguration) DeepCopy() *PostgresInstanceSettingsIpConfiguration {
	if in == nil {
		return nil
	}
	out := new(PostgresInstanceSettingsIpConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresInstanceSettingsLocationPreference) DeepCopyInto(out *PostgresInstanceSettingsLocationPreference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresInstanceSettingsLocationPreference.
func (in *PostgresInstanceSettingsLocationPreference) DeepCopy() *PostgresInstanceSettingsLocationPreference {
	if in == nil {
		return nil
	}
	out := new(PostgresInstanceSettingsLocationPreference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresInstanceSettingsMaintenanceWindow) DeepCopyInto(out *PostgresInstanceSettingsMaintenanceWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresInstanceSettingsMaintenanceWindow.
func (in *PostgresInstanceSettingsMaintenanceWindow) DeepCopy() *PostgresInstanceSettingsMaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(PostgresInstanceSettingsMaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresInstanceSettingsSpec) DeepCopyInto(out *PostgresInstanceSettingsSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DatabaseFlags != nil {
		in, out := &in.DatabaseFlags, &out.DatabaseFlags
		*out = make([]PostgresInstanceSettingsDatabaseFlags, len(*in))
		copy(*out, *in)
	}
	out.IpConfiguration = in.IpConfiguration
	out.BackupConfiguration = in.BackupConfiguration
	out.LocationPreference = in.LocationPreference
	out.MaintenanceWindow = in.MaintenanceWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresInstanceSettingsSpec.
func (in *PostgresInstanceSettingsSpec) DeepCopy() *PostgresInstanceSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresInstanceSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresqlInstanceBackend) DeepCopyInto(out *PostgresqlInstanceBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresqlInstanceBackend.
func (in *PostgresqlInstanceBackend) DeepCopy() *PostgresqlInstanceBackend {
	if in == nil {
		return nil
	}
	out := new(PostgresqlInstanceBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresqlInstanceProvider) DeepCopyInto(out *PostgresqlInstanceProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresqlInstanceProvider.
func (in *PostgresqlInstanceProvider) DeepCopy() *PostgresqlInstanceProvider {
	if in == nil {
		return nil
	}
	out := new(PostgresqlInstanceProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresqlInstanceSpec) DeepCopyInto(out *PostgresqlInstanceSpec) {
	*out = *in
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PostgresInstanceSettingsSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresqlInstanceSpec.
func (in *PostgresqlInstanceSpec) DeepCopy() *PostgresqlInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresqlInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresqlInstanceStorageBucket) DeepCopyInto(out *PostgresqlInstanceStorageBucket) {
	*out = *in
	in.LifecycleRule.DeepCopyInto(&out.LifecycleRule)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresqlInstanceStorageBucket.
func (in *PostgresqlInstanceStorageBucket) DeepCopy() *PostgresqlInstanceStorageBucket {
	if in == nil {
		return nil
	}
	out := new(PostgresqlInstanceStorageBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresqlInstanceStorageBucketLifecycleRules) DeepCopyInto(out *PostgresqlInstanceStorageBucketLifecycleRules) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresqlInstanceStorageBucketLifecycleRules.
func (in *PostgresqlInstanceStorageBucketLifecycleRules) DeepCopy() *PostgresqlInstanceStorageBucketLifecycleRules {
	if in == nil {
		return nil
	}
	out := new(PostgresqlInstanceStorageBucketLifecycleRules)
	in.DeepCopyInto(out)
	return out
}
