
apiVersion: v1
kind: Service
metadata:
  name: terrak8s-webhook-service
  namespace: terrak8s-operator
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    control-plane: controller-manager
