# Default values for terrak8s-operator.
# This is a YAML-formatted file.
controller:
  name: terrak8s-controller

deadlineSeconds: 400

replicaCount: 2

# # Port on which controller is listening
ports:
- name: http
  containerPort: 8081
  protocol: TCP
- name: webhook
  containerPort: 8443
  protocol: TCP

# Probes configuration
livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 2
  successThreshold: 1
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /readyz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 1
  successThreshold: 1
  timeoutSeconds: 5


## See `kubectl explain poddisruptionbudget.spec` for more infos
podDisruptionBudget:
  maxUnavailable: 1


# Additional Volume
extraMountVolumes:
  - name: webhook-certs
    mountPath: /tmp/k8s-webhook-server/serving-certs
    secret: webhook-certs

## default resources
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 1Gi