apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-binding" .Values.controller.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-clusterrole" .Values.controller.name }}
subjects:
- kind: ServiceAccount
  name: {{ printf "sa-%s" .Values.controller.name }}
  namespace: {{ .Values.controller.namespace }}
