name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  linter:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v1.1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  builder:
    name: golang-builder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.10.0"
    - name: check cluster
      run: kubectl get po -n kube-system
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: fmt
      run: go fmt ./...
    - name: vet
      run: go vet ./...
    - name: test
      run: go test ./...
    - name: build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -o bin/manager main.go
