name: release

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch-tag
        run: echo ::set-output release=TAG::$(shell git describe --exact-match --abbrev=0 2>/dev/null || echo "")
        id: tag
      - name: Prepare helm chart
        run: |
          sed -i -e 's/version: 0.1.0*/version: ${{ steps.tag.outputs.TAG }}/' chart/terrak8/Chart.yaml
          sed -i -e 's/appVersion: 0.1.0*/appVersion: ${{ steps.tag.outputs.TAG }}/' chart/terrak8/Chart.yaml
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint chart/terrak8s
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hamzazo/terrak8s-operator:${{ steps.tag.outputs.TAG }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          release_name: Release - v${{ steps.tag.outputs.TAG }}
          draft: false
          prerelease: false